### ISSUE TITLE
Decorators do not work when using custom `.swcrc` instead of `tsconfig.json`

### ISSUE THREAD

**Issue by ValentinGurkov** [unplugin/unplugin-swc#106]
### Describe the bug

The support for custom `.swcrc` file does not support decorators.

I have created a sample repo based on this repo which can be found at https://github.com/ValentinGurkov/unplugin-swc-decorator-error.

I changed the build step to build via `tsc` since `tsup` does not support decorators.

Then I added an extra class with decorator metadata to `test/fixtures/custom-swcrc/index.tsx`. I used the package `class-validator` for an example decorator since I found this the quickest way to create an example.

```ts
import { IsDefined } from "class-validator";

class User {
  @IsDefined()
  name!: string;
}
```

If you run the tests, the `custom swcrc` will fail with:

```
FAIL  test/index.test.ts > custom swcrc
Error:
  × Unexpected token `@`. Expected identifier, string literal, numeric literal or [ for the computed key
   ╭─[D:\Projects\unplugin-swc-main\test\fixtures\custom-swcrc\index.tsx:2:1]
 2 │ import { IsDefined } from "class-validator";
 3 │
 4 │ class User {
 5 │   @IsDefined()
   ·   ─
 6 │   name!: string;
 7 │ }
   ╰────


Caused by:
    Syntax Error
```

I managed to modify the `src/index.ts` to get things to compile but am I no expert on this, neither I understand the reason completely.

But it has something to do with passing the empty `jsc`  object to `transform`.

If you navigate to `src/index.ts`, comment the code from line 90 to 95:
```ts
const result = await transform(code, {
  filename: id,
  sourceMaps: true,
  ...options,
  jsc,
})
```

```diff
-const result = await transform(code, {
-  filename: id,
-  sourceMaps: true,
-  ...options,
-  jsc,
-})

+//const result = await transform(code, {
+//  filename: id,
+//  sourceMaps: true,
+//  ...options,
+//  jsc,
+//})

```

And remove the comments from the code from line 97 to line 113, so it is active:
```ts
let result
if (tsconfigFile === false) { 
  const newJsc: any = JSON.parse(readFileSync(path.r
  result = await transform(code, {
    filename: id,
    sourceMaps: true,
    ...options,
    jsc: newJsc,
  })
} else {
  result = await transform(code, {
    filename: id,
    sourceMaps: true,
    ...options,
    jsc,
  })
}
```

```diff
-//let result
-//if (tsconfigFile === false) { 
-//  const newJsc: any = JSON.parse(readFileSync(path.r
-//  result = await transform(code, {
-//    filename: id,
-//    sourceMaps: true,
-//    ...options,
-//    jsc: newJsc,
-//  })
-//} else {
-//  result = await transform(code, {
-//    filename: id,
-//    sourceMaps: true,
-//    ...options,
-//    jsc,
-//  })
-//}

+let result
+if (tsconfigFile === false) { 
+  const newJsc: any = JSON.parse(readFileSync(path.r
+  result = await transform(code, {
+    filename: id,
+    sourceMaps: true,
+    ...options,
+    jsc: newJsc,
+  })
+} else {
+  result = await transform(code, {
+    filename: id,
+    sourceMaps: true,
+    ...options,
+    jsc,
+  })
+}
```

And run the tests, all tests will pass.

The way I've adjusted things in a really dirty way so to read the `.swcrc` file and pass all settings this way.

I've tried not sending the `jsc` argument at all and on this repository the test still failed. On a very large custom repository, which I can't share, I had commented the `jsc` argument and everything seemed to work, so I expected this was the solution but it did not work here.

I want to share my findings here, hopefully someone with more understanding on SWC transformations can help out and we can design a solution that supports decorators when using `.swcrc` instead of `tsconfig.json`

### Reproduction

https://github.com/ValentinGurkov/unplugin-swc-decorator-error

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 9.24 GB / 31.21 GB
  Binaries:
    Node: 20.11.0 - C:\program files\nodejs\node.EXE
    npm: 10.2.4 - C:\program files\nodejs\npm.CMD
    pnpm: 8.15.3 - C:\program files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.128)
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hannoeru** [comment]
You can disable tsconfig overwrite by setting `tsconfigFile` to `false`.
