### ISSUE TITLE
Ignore `target` from tsconfig when `env` is set in SWC config

### ISSUE THREAD

**Issue by yjaaidi** [unplugin/unplugin-swc#137]
### Clear and concise description of the problem

When `env` is set in SWC configuration and `compilerOptions.target` is set in tsconfig, SWC will produce the following error:
```Error: `env` and `jsc.target` cannot be used together```

### Suggested solution

Do not set `jsc.target` to `compilerOptions.target` if `env` option is provided.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hannoeru** [comment]
You can set `tsconfigFile: false` to enforce using .swcrc configs for better integration.
