### ISSUE TITLE
Internal server error: unknown variant ``ESNext``

### ISSUE THREAD

**Issue by KiddoV** [unplugin/unplugin-swc#93]
### Describe the bug

When you set your ``compilerOptions.target: "ESNext"`` in ``tsconfig.ts`` file. This will throw an error:
```console
6:30:56 AM [vite] Internal server error: unknown variant `ESNext`, expected one of `es3`, `es5`, `es2015`, `es2016`, `es2017`, `es2018`, `es2019`, `es2020`, `es2021`, `es2022`, `esnext` at line 1 column 241
  Plugin: swc
  File: .../src/main.ts

6:30:56 AM [vite] Pre-transform error: unknown variant `ESNext`, expected one of `es3`, `es5`, `es2015`, `es2016`, `es2017`, `es2018`, `es2019`, `es2020`, `es2021`, `es2022`, `esnext` at line 1 column 241
```

My ``vite.config.ts``
```ts
import { defineConfig } from 'vite';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import sveltePreprocess from 'svelte-preprocess';
import swc from 'unplugin-swc';

// https://vitejs.dev/config/
export default defineConfig({
	plugins: [
		swc.vite(),
		svelte({
			preprocess: sveltePreprocess({
				// Enable strict prop checking
				strictProps: false,
			}),
		}),
	],
})
```

I am expecting "ESNext" and "esnext" should be the same.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-43qo9n?file=vite.config.ts

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Memory: 7.59 GB / 31.89 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.77)
    Internet Explorer: 11.0.19041.3636
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Jerome1337** [comment]
Any info?

**Comment by hannoeru** [comment]
https://github.com/swc-project/swc/pull/8653
